export type SettingsSearchEntry = {
  key: string;
  title: string;
  titleEn?: string;
  path: string;
  section: string;
  keywords: string[];
  description?: string;
  descriptionEn?: string;
};

export const settingsSearchIndex: SettingsSearchEntry[] = [
  {
    key: "workout.today.log",
    title: "오늘 운동 로그",
    titleEn: "Today's Workout Log",
    path: "/workout/log",
    section: "훈련",
    keywords: ["운동", "로그", "세트", "저장", "sync", "today"],
    description: "오늘 세션 생성, 기록, 저장",
    descriptionEn: "Create, record, and save today's session",
  },
  {
    key: "workout.today.overrides",
    title: "세션 오버라이드",
    titleEn: "Session Overrides",
    path: "/workout/today/overrides",
    section: "훈련",
    keywords: ["오버라이드", "교체", "보조 운동", "override"],
    description: "교체/보조 운동 규칙 설정",
    descriptionEn: "Configure substitution and assistance rules",
  },
  {
    key: "calendar.options",
    title: "캘린더 옵션",
    titleEn: "Calendar Options",
    path: "/calendar/options",
    section: "훈련",
    keywords: ["캘린더", "옵션", "보기", "열기 동작", "timezone"],
    description: "보기 방식과 열기 동작 설정",
    descriptionEn: "Configure view mode and open behavior",
  },
  {
    key: "calendar.options.view-mode",
    title: "보기 방식",
    titleEn: "View Mode",
    path: "/calendar/options/select/view-mode",
    section: "훈련",
    keywords: ["월", "주", "month", "week", "그리드"],
    description: "month/week 표시 방식",
    descriptionEn: "Choose month/week presentation",
  },
  {
    key: "calendar.options.timezone",
    title: "캘린더 시간대",
    titleEn: "Calendar Time Zone",
    path: "/calendar/options/select/timezone",
    section: "훈련",
    keywords: ["timezone", "시간대", "UTC", "date boundary"],
    description: "날짜 경계 시간대 설정",
    descriptionEn: "Set the time zone for date boundaries",
  },
  {
    key: "calendar.options.auto-open",
    title: "열기 동작",
    titleEn: "Open Behavior",
    path: "/calendar/options/select/auto-open",
    section: "훈련",
    keywords: ["auto generate", "open only", "자동 생성", "열기"],
    description: "날짜 열기 시 생성 여부 설정",
    descriptionEn: "Choose whether opening a date also generates a session",
  },
  {
    key: "calendar.options.open-time",
    title: "기본 열기 시간",
    titleEn: "Default Open Time",
    path: "/calendar/options/picker/open-time",
    section: "훈련",
    keywords: ["open time", "시간", "picker", "시각"],
    description: "날짜 열기 기본 시간",
    descriptionEn: "Set the default time used when opening a date",
  },
  {
    key: "plans.manage",
    title: "내 플랜",
    titleEn: "My Plans",
    path: "/plans",
    section: "프로그램",
    keywords: ["플랜", "관리", "1RM", "TM", "program"],
    description: "활성 플랜 관리 · 1RM/TM 조정",
    descriptionEn: "Manage active plans and tune 1RM/TM",
  },
  {
    key: "plans.history",
    title: "수행 히스토리",
    titleEn: "Workout History",
    path: "/plans/history",
    section: "프로그램",
    keywords: ["history", "logs", "수행", "기록"],
    description: "플랜별 수행 로그 타임라인",
    descriptionEn: "Per-plan workout log timeline",
  },
  {
    key: "stats.dashboard",
    title: "통계 대시보드",
    titleEn: "Stats Dashboard",
    path: "/stats/dashboard",
    section: "분석",
    keywords: ["stats", "volume", "pr", "dashboard"],
    description: "볼륨/PR 지표",
    descriptionEn: "Volume and PR metrics",
  },
  {
    key: "settings.exercise-management",
    title: "운동종목 관리",
    titleEn: "Exercise Management",
    path: "/settings/exercise-management",
    section: "시스템",
    keywords: ["exercise", "catalog", "운동종목", "추가", "수정", "삭제", "dropdown"],
    description: "운동종목 카탈로그 관리 및 추가 화면 연동",
    descriptionEn: "Manage the exercise catalog and add-screen integration",
  },
  {
    key: "settings.data-export",
    title: "데이터 내보내기",
    titleEn: "Data Export",
    path: "/settings/data",
    section: "시스템",
    keywords: ["백업", "export", "json", "csv", "다운로드"],
    description: "운동 데이터 파일 다운로드",
    descriptionEn: "Download workout data files",
  },
  {
    key: "settings.save-policy",
    title: "저장 정책",
    titleEn: "Save Policy",
    path: "/settings/save-policy",
    section: "시스템",
    keywords: ["optimistic", "rollback", "저장", "실패", "row lock"],
    description: "즉시 반영/롤백 정책",
    descriptionEn: "Optimistic update and rollback policy",
  },
  {
    key: "settings.selection-template",
    title: "선택 템플릿",
    titleEn: "Selection Templates",
    path: "/settings/selection-template",
    section: "시스템",
    keywords: ["selection", "search", "picker", "radio", "multi"],
    description: "선택/입력 템플릿 샘플",
    descriptionEn: "Selection and input template samples",
  },
  {
    key: "settings.ux-thresholds",
    title: "UX 기준치",
    titleEn: "UX Thresholds",
    path: "/settings/ux-thresholds",
    section: "시스템",
    keywords: ["ux", "threshold", "baseline", "전환율", "임계치", "compare"],
    description: "UX 퍼널/행동 기준치 조정",
    descriptionEn: "Adjust UX funnel and behavior thresholds",
  },
];
