export type SettingsSearchEntry = {
  key: string;
  title: string;
  titleEn?: string;
  path: string;
  section: string;
  keywords: string[];
  description?: string;
  descriptionEn?: string;
};

export const settingsSearchIndex: SettingsSearchEntry[] = [
  {
    key: "workout.today.log",
    title: "오늘 운동 로그",
    titleEn: "Today's Workout Log",
    path: "/workout/log",
    section: "훈련",
    keywords: ["운동", "로그", "세트", "저장", "sync", "today"],
    description: "오늘 세션 생성, 기록, 저장",
    descriptionEn: "Create, record, and save today's session",
  },
  {
    key: "workout.today.overrides",
    title: "세션 오버라이드",
    titleEn: "Session Overrides",
    path: "/workout/today/overrides",
    section: "훈련",
    keywords: ["오버라이드", "교체", "보조 운동", "override"],
    description: "교체/보조 운동 규칙 설정",
    descriptionEn: "Configure substitution and assistance rules",
  },
  {
    key: "calendar.options",
    title: "캘린더 옵션",
    titleEn: "Calendar Options",
    path: "/calendar/options",
    section: "훈련",
    keywords: ["캘린더", "옵션", "보기", "열기 동작", "timezone"],
    description: "보기 방식과 열기 동작 설정",
    descriptionEn: "Configure view mode and open behavior",
  },
  {
    key: "calendar.options.view-mode",
    title: "보기 방식",
    titleEn: "View Mode",
    path: "/calendar/options/select/view-mode",
    section: "훈련",
    keywords: ["월", "주", "month", "week", "그리드"],
    description: "month/week 표시 방식",
    descriptionEn: "Choose month/week presentation",
  },
  {
    key: "calendar.options.timezone",
    title: "캘린더 시간대",
    titleEn: "Calendar Time Zone",
    path: "/calendar/options/select/timezone",
    section: "훈련",
    keywords: ["timezone", "시간대", "UTC", "date boundary"],
    description: "날짜 경계 시간대 설정",
    descriptionEn: "Set the time zone for date boundaries",
  },
  {
    key: "calendar.options.auto-open",
    title: "열기 동작",
    titleEn: "Open Behavior",
    path: "/calendar/options/select/auto-open",
    section: "훈련",
    keywords: ["auto generate", "open only", "자동 생성", "열기"],
    description: "날짜 열기 시 생성 여부 설정",
    descriptionEn: "Choose whether opening a date also generates a session",
  },
  {
    key: "calendar.options.open-time",
    title: "기본 열기 시간",
    titleEn: "Default Open Time",
    path: "/calendar/options/picker/open-time",
    section: "훈련",
    keywords: ["open time", "시간", "picker", "시각"],
    description: "날짜 열기 기본 시간",
    descriptionEn: "Set the default time used when opening a date",
  },
  {
    key: "plans.manage",
    title: "플랜 워크스페이스",
    titleEn: "Plan Workspace",
    path: "/plans/manage",
    section: "프로그램",
    keywords: ["플랜", "생성", "generate", "program"],
    description: "플랜 생성/선택/실행",
    descriptionEn: "Create, select, and run plans",
  },
  {
    key: "plans.create",
    title: "플랜 만들기",
    titleEn: "Create Plan",
    path: "/plans/create",
    section: "프로그램",
    keywords: ["single", "composite", "manual", "생성"],
    description: "플랜 생성 방식 선택",
    descriptionEn: "Choose how to create a plan",
  },
  {
    key: "plans.context",
    title: "생성 컨텍스트",
    titleEn: "Generation Context",
    path: "/plans/context",
    section: "프로그램",
    keywords: ["context", "userId", "startDate", "timezone", "week", "day"],
    description: "생성 기본값 설정",
    descriptionEn: "Set generation defaults",
  },
  {
    key: "plans.context.user-id",
    title: "사용자 ID",
    titleEn: "User ID",
    path: "/plans/context/select/user-id",
    section: "프로그램",
    keywords: ["user", "scope", "owner", "사용자"],
    description: "생성 대상 사용자 범위",
    descriptionEn: "Choose the user scope for generation",
  },
  {
    key: "plans.context.start-date",
    title: "시작 날짜",
    titleEn: "Start Date",
    path: "/plans/context/picker/start-date",
    section: "프로그램",
    keywords: ["start date", "날짜", "기준일"],
    description: "생성 기준 날짜 설정",
    descriptionEn: "Set the reference start date",
  },
  {
    key: "plans.context.timezone",
    title: "생성 시간대",
    titleEn: "Generation Time Zone",
    path: "/plans/context/select/timezone",
    section: "프로그램",
    keywords: ["timezone", "UTC", "시간대", "date boundary"],
    description: "날짜 경계 시간대 설정",
    descriptionEn: "Set the time zone for date boundaries",
  },
  {
    key: "plans.context.session-key-mode",
    title: "세션 키 방식",
    titleEn: "Session Key Mode",
    path: "/plans/context/select/session-key-mode",
    section: "프로그램",
    keywords: ["DATE", "LEGACY", "session key", "WnDn"],
    description: "세션 키 포맷 선택",
    descriptionEn: "Choose the session-key format",
  },
  {
    key: "plans.context.week",
    title: "주차",
    titleEn: "Week",
    path: "/plans/context/picker/week",
    section: "프로그램",
    keywords: ["week", "주차", "number"],
    description: "생성 주차 인덱스",
    descriptionEn: "Set the generation week index",
  },
  {
    key: "plans.context.day",
    title: "일차",
    titleEn: "Day",
    path: "/plans/context/picker/day",
    section: "프로그램",
    keywords: ["day", "일차", "number"],
    description: "생성 일차 인덱스",
    descriptionEn: "Set the generation day index",
  },
  {
    key: "templates.manage",
    title: "템플릿 워크스페이스",
    titleEn: "Template Workspace",
    path: "/templates/manage",
    section: "프로그램",
    keywords: ["템플릿", "버전", "fork", "template", "version"],
    description: "템플릿/버전 관리",
    descriptionEn: "Manage templates and versions",
  },
  {
    key: "stats.dashboard",
    title: "통계 대시보드",
    titleEn: "Stats Dashboard",
    path: "/stats/dashboard",
    section: "분석",
    keywords: ["stats", "volume", "compliance", "pr", "dashboard"],
    description: "볼륨/준수율/PR 지표",
    descriptionEn: "Volume, compliance, and PR metrics",
  },
  {
    key: "settings.exercise-management",
    title: "운동종목 관리",
    titleEn: "Exercise Management",
    path: "/settings/exercise-management",
    section: "시스템",
    keywords: ["exercise", "catalog", "운동종목", "추가", "수정", "삭제", "dropdown"],
    description: "운동종목 카탈로그 관리 및 추가 화면 연동",
    descriptionEn: "Manage the exercise catalog and add-screen integration",
  },
  {
    key: "settings.data-export",
    title: "데이터 내보내기",
    titleEn: "Data Export",
    path: "/settings/data",
    section: "시스템",
    keywords: ["백업", "export", "json", "csv", "다운로드"],
    description: "운동 데이터 파일 다운로드",
    descriptionEn: "Download workout data files",
  },
  {
    key: "settings.save-policy",
    title: "저장 정책",
    titleEn: "Save Policy",
    path: "/settings/save-policy",
    section: "시스템",
    keywords: ["optimistic", "rollback", "저장", "실패", "row lock"],
    description: "즉시 반영/롤백 정책",
    descriptionEn: "Optimistic update and rollback policy",
  },
  {
    key: "settings.selection-template",
    title: "선택 템플릿",
    titleEn: "Selection Templates",
    path: "/settings/selection-template",
    section: "시스템",
    keywords: ["selection", "search", "picker", "radio", "multi"],
    description: "선택/입력 템플릿 샘플",
    descriptionEn: "Selection and input template samples",
  },
  {
    key: "settings.ux-thresholds",
    title: "UX 기준치",
    titleEn: "UX Thresholds",
    path: "/settings/ux-thresholds",
    section: "시스템",
    keywords: ["ux", "threshold", "baseline", "전환율", "임계치", "compare"],
    description: "UX 퍼널/행동 기준치 조정",
    descriptionEn: "Adjust UX funnel and behavior thresholds",
  },
];
