export type SettingsSearchEntry = {
  key: string;
  title: string;
  path: string;
  section: string;
  keywords: string[];
  description?: string;
};

export const settingsSearchIndex: SettingsSearchEntry[] = [
  {
    key: "workout.today.log",
    title: "오늘 운동 로그",
    path: "/workout/today/log",
    section: "훈련",
    keywords: ["운동", "로그", "세트", "저장", "sync", "today"],
    description: "오늘 세션 생성, 기록, 저장",
  },
  {
    key: "workout.today.overrides",
    title: "세션 오버라이드",
    path: "/workout/today/overrides",
    section: "훈련",
    keywords: ["오버라이드", "교체", "보조 운동", "override"],
    description: "교체/보조 운동 규칙 설정",
  },
  {
    key: "calendar.manage",
    title: "캘린더 워크스페이스",
    path: "/calendar/manage",
    section: "훈련",
    keywords: ["캘린더", "날짜", "세션 생성", "calendar"],
    description: "날짜별 세션 생성/열기",
  },
  {
    key: "calendar.options",
    title: "캘린더 옵션",
    path: "/calendar/options",
    section: "훈련",
    keywords: ["캘린더", "옵션", "보기", "열기 동작", "timezone"],
    description: "보기 방식과 열기 동작 설정",
  },
  {
    key: "calendar.options.view-mode",
    title: "보기 방식",
    path: "/calendar/options/select/view-mode",
    section: "훈련",
    keywords: ["월", "주", "month", "week", "그리드"],
    description: "month/week 표시 방식",
  },
  {
    key: "calendar.options.timezone",
    title: "캘린더 시간대",
    path: "/calendar/options/select/timezone",
    section: "훈련",
    keywords: ["timezone", "시간대", "UTC", "date boundary"],
    description: "날짜 경계 시간대 설정",
  },
  {
    key: "calendar.options.auto-open",
    title: "열기 동작",
    path: "/calendar/options/select/auto-open",
    section: "훈련",
    keywords: ["auto generate", "open only", "자동 생성", "열기"],
    description: "날짜 열기 시 생성 여부 설정",
  },
  {
    key: "calendar.options.open-time",
    title: "기본 열기 시간",
    path: "/calendar/options/picker/open-time",
    section: "훈련",
    keywords: ["open time", "시간", "picker", "시각"],
    description: "날짜 열기 기본 시간",
  },
  {
    key: "plans.manage",
    title: "플랜 워크스페이스",
    path: "/plans/manage",
    section: "프로그램",
    keywords: ["플랜", "생성", "generate", "program"],
    description: "플랜 생성/선택/실행",
  },
  {
    key: "plans.create",
    title: "플랜 만들기",
    path: "/plans/create",
    section: "프로그램",
    keywords: ["single", "composite", "manual", "생성"],
    description: "플랜 생성 방식 선택",
  },
  {
    key: "plans.context",
    title: "생성 컨텍스트",
    path: "/plans/context",
    section: "프로그램",
    keywords: ["context", "userId", "startDate", "timezone", "week", "day"],
    description: "생성 기본값 설정",
  },
  {
    key: "plans.context.user-id",
    title: "사용자 ID",
    path: "/plans/context/select/user-id",
    section: "프로그램",
    keywords: ["user", "scope", "owner", "사용자"],
    description: "생성 대상 사용자 범위",
  },
  {
    key: "plans.context.start-date",
    title: "시작 날짜",
    path: "/plans/context/picker/start-date",
    section: "프로그램",
    keywords: ["start date", "날짜", "기준일"],
    description: "생성 기준 날짜 설정",
  },
  {
    key: "plans.context.timezone",
    title: "생성 시간대",
    path: "/plans/context/select/timezone",
    section: "프로그램",
    keywords: ["timezone", "UTC", "시간대", "date boundary"],
    description: "날짜 경계 시간대 설정",
  },
  {
    key: "plans.context.session-key-mode",
    title: "세션 키 방식",
    path: "/plans/context/select/session-key-mode",
    section: "프로그램",
    keywords: ["DATE", "LEGACY", "session key", "WnDn"],
    description: "세션 키 포맷 선택",
  },
  {
    key: "plans.context.week",
    title: "주차",
    path: "/plans/context/picker/week",
    section: "프로그램",
    keywords: ["week", "주차", "number"],
    description: "생성 주차 인덱스",
  },
  {
    key: "plans.context.day",
    title: "일차",
    path: "/plans/context/picker/day",
    section: "프로그램",
    keywords: ["day", "일차", "number"],
    description: "생성 일차 인덱스",
  },
  {
    key: "templates.manage",
    title: "템플릿 워크스페이스",
    path: "/templates/manage",
    section: "프로그램",
    keywords: ["템플릿", "버전", "fork", "template", "version"],
    description: "템플릿/버전 관리",
  },
  {
    key: "stats.dashboard",
    title: "통계 대시보드",
    path: "/stats/dashboard",
    section: "분석",
    keywords: ["stats", "volume", "compliance", "pr", "dashboard"],
    description: "볼륨/준수율/PR 지표",
  },
  {
    key: "stats.filters",
    title: "통계 필터",
    path: "/stats/filters",
    section: "분석",
    keywords: ["filter", "plan", "bucket", "exercise", "days"],
    description: "통계 조회 범위 설정",
  },
  {
    key: "stats.filters.plan-scope",
    title: "플랜 필터",
    path: "/stats/filters/select/plan-scope",
    section: "분석",
    keywords: ["plan scope", "플랜 범위", "all"],
    description: "플랜 집계 범위",
  },
  {
    key: "stats.filters.bucket",
    title: "집계 단위",
    path: "/stats/filters/select/bucket",
    section: "분석",
    keywords: ["bucket", "day", "week", "month", "집계"],
    description: "일/주/월 집계 단위",
  },
  {
    key: "stats.filters.exercise",
    title: "운동 필터",
    path: "/stats/filters/select/exercise",
    section: "분석",
    keywords: ["exercise", "운동", "search", "e1RM"],
    description: "운동 기준 필터",
  },
  {
    key: "stats.filters.metrics",
    title: "지표 선택",
    path: "/stats/filters/select/metrics",
    section: "분석",
    keywords: ["metrics", "e1rm", "volume", "compliance", "prs"],
    description: "표시할 지표 섹션",
  },
  {
    key: "stats.filters.days",
    title: "기본 일수",
    path: "/stats/filters/picker/days",
    section: "분석",
    keywords: ["days", "기간", "range"],
    description: "기본 조회 일수",
  },
  {
    key: "stats.filters.from",
    title: "시작일",
    path: "/stats/filters/picker/from",
    section: "분석",
    keywords: ["from", "start", "시작"],
    description: "조회 시작 날짜",
  },
  {
    key: "stats.filters.to",
    title: "종료일",
    path: "/stats/filters/picker/to",
    section: "분석",
    keywords: ["to", "end", "종료"],
    description: "조회 종료 날짜",
  },
  {
    key: "settings.data-export",
    title: "데이터 내보내기",
    path: "/settings/data",
    section: "시스템",
    keywords: ["백업", "export", "json", "csv", "다운로드"],
    description: "운동 데이터 파일 다운로드",
  },
  {
    key: "settings.save-policy",
    title: "저장 정책",
    path: "/settings/save-policy",
    section: "시스템",
    keywords: ["optimistic", "rollback", "저장", "실패", "row lock"],
    description: "즉시 반영/롤백 정책",
  },
  {
    key: "settings.selection-template",
    title: "선택 템플릿",
    path: "/settings/selection-template",
    section: "시스템",
    keywords: ["selection", "search", "picker", "radio", "multi"],
    description: "선택/입력 템플릿 샘플",
  },
  {
    key: "offline.help",
    title: "오프라인 도움말",
    path: "/offline",
    section: "시스템",
    keywords: ["offline", "queue", "sync", "복구"],
    description: "오프라인 저장/복구 안내",
  },
];
