export const APP_ROUTES = {
  home: "/",
  plansHome: "/plans",
  plansHistory: "/plans/history",
  programStore: "/program-store",
  programCreate: "/program-store/create",
  calendarHome: "/calendar",
  calendarOptions: "/calendar/options",
  todayHome: "/workout/today",
  todayLog: "/workout/log",
  todayOverrides: "/workout/today/overrides",
  workoutRecord: "/workout/log",
  statsHome: "/stats",
  systemStats: "/settings/system-stats",
} as const;
