export const APP_ROUTES = {
  home: "/",
  plansHome: "/plans",
  plansManage: "/plans/manage",
  plansCreateGuide: "/plans/create",
  plansContext: "/plans/context",
  plansHistory: "/plans/history",
  programStore: "/program-store",
  programCreate: "/program-store/create",
  templatesHome: "/templates",
  templatesManage: "/templates/manage",
  calendarHome: "/calendar",
  calendarOptions: "/calendar/options",
  todayHome: "/workout/today",
  todayLog: "/workout-record",
  todayOverrides: "/workout/today/overrides",
  workoutRecord: "/workout-record",
  statsHome: "/stats",
  statsDashboard: "/stats/dashboard",
  stats1rm: "/stats-1rm",
  statsFilters: "/stats/filters",
} as const;
