export const APP_ROUTES = {
  home: "/",
  plansHome: "/plans",
  plansManage: "/plans/manage",
  plansCreateGuide: "/plans/create",
  plansContext: "/plans/context",
  plansHistory: "/plans/history",
  programStore: "/program-store",
  programCreate: "/program-store/create",
  calendarHome: "/calendar",
  calendarOptions: "/calendar/options",
  todayLog: "/workout/log",
  todayOverrides: "/workout/log/overrides",
  workoutRecord: "/workout/log",
  exercisesHome: "/exercises",
  statsHome: "/stats",
  prHistory: "/stats/prs",
  exerciseDetail: (exerciseId: string) => `/exercises/${encodeURIComponent(exerciseId)}`,
  systemStats: "/settings/system-stats",
} as const;
